tasks:
  - before: |
      # Only the /workspace folder is persistent
      # HLS uses XDG specification for cache directories, here we also set
      # a good default for the other XDG directories
      cat <<HERE > $HOME/.bashrc.d/210-haskell
      export CABAL_DIR=/workspace/.cabal
      export STACK_ROOT=/workspace/.stack
      export GHCUP_INSTALL_BASE_PREFIX=/workspace
      export XDG_CACHE_HOME=/workspace/.cache
      export XDG_CONFIG_HOME=/workspace/.config
      export XDG_DATA_HOME=/workspace/.local/share
      export XDG_STATE_HOME=/workspace/.local/state
      HERE

      # Use the same environment variables in this shell session
      source $HOME/.bashrc.d/210-haskell

      curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 BOOTSTRAP_HASKELL_VERBOSE=1 BOOTSTRAP_HASKELL_GHC_VERSION=9.0.2 sh
      $GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin/ghcup install ghc 9.0.2 --set
      $GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin/ghcup install cabal
      $GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin/ghcup install stack
      $GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin/ghcup install hls

      # Add ghcup binaries to the PATH since VSCode does not see 'source .ghcup/env'
      pushd /usr/local/bin
      sudo ln -s /workspace/.ghcup/bin/* /usr/local/bin
      popd

      # Fix the Cabal dir since VSCode does not see CABAL_DIR
      cabal user-config init
      echo "Symlinking /workspace/.cabal to ~/.cabal"
      ln -s /workspace/.cabal ~/.cabal

    init: |
      stack test

    command: |
      stack test
vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell@3.3.0
